// See DOTA_GameMode in dota/dota_shared_enums.proto
// Also: https://github.com/odota/web/blob/master/src/lang/en-US.json
export default {
  0: { name: 'Unknown' },
  1: { name: 'All Pick' },
  2: { name: 'Captains Mode' },
  3: { name: 'Random Draft' },
  4: { name: 'Single Draft' },
  5: { name: 'All Random' },
  6: { name: 'Intro' },
  7: { name: 'Diretide' },
  8: { name: 'Reverse Captains Mode' },
  9: { name: 'The Greeviling' },
  10: { name: 'Tutorial' },
  11: { name: 'Mid Only' },
  12: { name: 'Least Played' },
  13: { name: 'Limited Heroes' },
  14: { name: 'Compendium' },
  15: { name: 'Custom' },
  16: { name: 'Captains Draft' },
  17: { name: 'Balanced Draft' },
  18: { name: 'Ability Draft' },
  19: { name: 'Event' },
  20: { name: 'All Random Deathmatch' },
  21: { name: '1v1 Solo Mid' },
  22: { name: 'All Draft' },
  23: { name: 'Turbo' },
  24: { name: 'Mutation' },
  25: { name: 'Coaches Challenge' },
};
